# Generated by Django 6.0.6 on 2026-07-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0013_tag_cafe_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
