# Generated by Django 6.0.6 on 2026-07-27 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0014_alter_tag_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cafe',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='rating',
        ),
    ]
