# Generated by Django 6.0.6 on 2026-07-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0015_alter_cafe_options_remove_cafe_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='cafes.tag'),
        ),
    ]
