# Generated by Django 6.0.6 on 2026-07-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0016_alter_cafe_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='tags',
            field=models.ManyToManyField(related_name='cafes', to='cafes.tag'),
        ),
    ]
