# Generated by Django 6.0.6 on 2026-07-30 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0017_alter_cafe_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='new_barrio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cafes', to='cafes.barrio'),
        ),
    ]
