# Generated by Django 6.0.6 on 2026-07-30 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0019_transfer_barrio_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='barrio',
        ),
    ]
