# Generated by Django 6.0.6 on 2026-07-30 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0020_remove_cafe_barrio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafe',
            old_name='new_barrio',
            new_name='barrio',
        ),
    ]
