# Generated by Django 6.0.6 on 2026-07-30 13:46

from django.db import migrations
from django.utils.text import slugify

def fill_slugs(apps, schema_editor):
    Barrio = apps.get_model('cafes', 'Barrio')

    for barrio in Barrio.objects.all():
        barrio.slug = slugify(barrio.name)
        barrio.save()

    Barrio.objects.get_or_create(name="Almagro", slug=slugify("Almagro"), defaults={"comuna": 5})

class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0023_barrio_slug'),
    ]

    operations = [migrations.RunPython(fill_slugs)
    ]
